/**
 * Differential test between the TypeScript checker and the Solidity policy.
 *
 * No expected-result function is consulted anywhere in this file. Batches are generated by a
 * seeded PRNG and mutated blindly; the only assertion is that the two independent implementations
 * return identical five-tuples. A bug present in both would survive this test, which is why the
 * fixture tests (checked against hand-written expectations) exist alongside it.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { evaluate } from "../src/shared/policy.ts";
import { harness, type Harness } from "./helpers.ts";
import type { RecordRow } from "../src/shared/types.ts";

function makeRng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >> 17;
    s ^= s << 5; s >>>= 0;
    return s / 0x100000000;
  };
}

const EDGE_IDS = [0n, 1n, 2n ** 31n - 1n, 2n ** 31n, 4294967295n];
const EDGE_PRICES = [0n, 1n, 2n ** 53n - 1n, 2n ** 63n, 18446744073709551615n];

function randomSource(rnd: () => number): RecordRow[] {
  const n = 1 + Math.floor(rnd() * 12);
  const ids = new Set<bigint>();
  while (ids.size < n) {
    const useEdge = rnd() < 0.25;
    ids.add(useEdge ? EDGE_IDS[Math.floor(rnd() * EDGE_IDS.length)]! : BigInt(Math.floor(rnd() * 5000)));
  }
  return [...ids].map((productId) => ({
    productId,
    priceCents: rnd() < 0.25
      ? EDGE_PRICES[Math.floor(rnd() * EDGE_PRICES.length)]!
      : BigInt(Math.floor(rnd() * 1_000_000)),
  }));
}

/** Blind mutations. The test does not know or care which rule any of these will trip. */
function mutate(rows: RecordRow[], rnd: () => number): RecordRow[] {
  const out = rows.map((r) => ({ ...r }));
  const pick = () => Math.floor(rnd() * out.length);
  switch (Math.floor(rnd() * 8)) {
    case 0: return out;                                              // untouched
    case 1: out.splice(pick(), 1); return out;                       // drop a row
    case 2: { const i = pick(); out.push({ ...out[i]! }); return out; }
    case 3: { const i = pick(); out[i] = { ...out[i]!, priceCents: out[i]!.priceCents ^ 1n }; return out; }
    case 4: { const i = pick(); const j = pick(); const t = out[i]!; out[i] = out[j]!; out[j] = t; return out; }
    case 5: { const i = pick(); out[i] = { ...out[i]!, productId: 4294967295n }; return out; }
    case 6: out.push({ productId: BigInt(9000 + Math.floor(rnd() * 100)), priceCents: 42n }); return out;
    default: return [];                                              // empty delivery
  }
}

const sortAsc = (rows: RecordRow[]) => [...rows].sort((a, b) => (a.productId < b.productId ? -1 : a.productId > b.productId ? 1 : 0));

describe("checker parity: TypeScript vs Solidity, no expected-result function", () => {
  let h: Harness;
  beforeAll(async () => { h = await harness(); });
  afterAll(async () => { await h?.close(); });

  it("agrees on 300 generated batches", async () => {
    const rnd = makeRng(0xac3e7a11);
    const policy = h.dep.policy as any;
    const seen = new Set<string>();
    let compared = 0;

    for (let k = 0; k < 300; k++) {
      const source = randomSource(rnd);
      const base = rnd() < 0.5 ? sortAsc(source) : source;
      const output = mutate(base, rnd);
      const requiredRowCount = rnd() < 0.85 ? source.length : Math.floor(rnd() * 14);

      const ts = evaluate(source, output, requiredRowCount);
      const sol = await policy.evaluate(
        source.map((r) => [r.productId, r.priceCents]),
        output.map((r) => [r.productId, r.priceCents]),
        requiredRowCount,
        0x0f,
      );
      const solTuple = {
        verdict: Number(sol[0]), ruleId: Number(sol[1]), failCode: Number(sol[2]),
        detailA: BigInt(sol[3]), detailB: BigInt(sol[4]),
      };
      expect(
        { verdict: ts.verdict, ruleId: ts.ruleId, failCode: ts.failCode, detailA: ts.detailA, detailB: ts.detailB },
        `batch ${k}: source=${JSON.stringify(source, bigintJson)} output=${JSON.stringify(output, bigintJson)} required=${requiredRowCount}`,
      ).toEqual(solTuple);
      seen.add(`${solTuple.verdict}:${solTuple.ruleId}:${solTuple.failCode}`);
      compared++;
    }

    expect(compared).toBe(300);
    // The generator is only useful if it actually reaches the interesting states.
    for (const outcome of ["1:0:0", "2:1:1", "2:2:3", "2:2:4", "2:3:5", "2:4:6"]) {
      expect([...seen], `generated batches never reached outcome ${outcome}`).toContain(outcome);
    }
  });

  it("agrees on the non-default rule masks and out-of-bounds shapes", async () => {
    const policy = h.dep.policy as any;
    const src: RecordRow[] = [{ productId: 1n, priceCents: 5n }, { productId: 2n, priceCents: 6n }];
    const cases: Array<[RecordRow[], RecordRow[], number, number]> = [
      [src, src, 2, 0x0f],
      [src, src, 2, 0x07],
      [src, src, 3, 0x0f],
      [[], [], 0, 0x0f],
    ];
    for (const [s, o, n, mask] of cases) {
      const ts = evaluate(s, o, n, mask);
      const sol = await policy.evaluate(
        s.map((r) => [r.productId, r.priceCents]), o.map((r) => [r.productId, r.priceCents]), n, mask,
      );
      expect([ts.verdict, ts.ruleId, ts.failCode, ts.detailA, ts.detailB])
        .toEqual([Number(sol[0]), Number(sol[1]), Number(sol[2]), BigInt(sol[3]), BigInt(sol[4])]);
    }
  });
});

function bigintJson(_k: string, v: unknown) {
  return typeof v === "bigint" ? v.toString() : v;
}
