#!/usr/bin/env python3
"""
Independent generator for fixtures/golden-vectors.json.

Deliberately shares no code with the TypeScript encoder or with solc: the ABI layout is written
out by hand from docs/encoding.md section 2, and Keccak-256 is implemented from the permutation
spec below rather than imported. tests/encoding-parity.test.ts then checks that ethers and the
deployed Solidity contract both reproduce these bytes and digests.

Run: python3 scripts/gen-golden-vectors.py
"""
import json, pathlib

# ---------------------------------------------------------------- Keccak-256
RC = [0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
      0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
      0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
      0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
      0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
      0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008]
ROT = [[0, 36, 3, 41, 18], [1, 44, 10, 45, 2], [62, 6, 43, 15, 61],
       [28, 55, 25, 21, 56], [27, 20, 39, 8, 14]]
M = (1 << 64) - 1

def rol(x, n):
    n %= 64
    return ((x << n) | (x >> (64 - n))) & M

def keccak_f(a):
    for rnd in range(24):
        c = [a[x][0] ^ a[x][1] ^ a[x][2] ^ a[x][3] ^ a[x][4] for x in range(5)]
        d = [c[(x - 1) % 5] ^ rol(c[(x + 1) % 5], 1) for x in range(5)]
        for x in range(5):
            for y in range(5):
                a[x][y] ^= d[x]
        b = [[0] * 5 for _ in range(5)]
        for x in range(5):
            for y in range(5):
                b[y][(2 * x + 3 * y) % 5] = rol(a[x][y], ROT[x][y])
        for x in range(5):
            for y in range(5):
                a[x][y] = b[x][y] ^ ((~b[(x + 1) % 5][y] & M) & b[(x + 2) % 5][y])
        a[0][0] ^= RC[rnd]
    return a

def keccak256(data: bytes) -> str:
    rate = 136
    padded = bytearray(data)
    padded.append(0x01)                      # Keccak domain suffix (SHA3 would be 0x06)
    while len(padded) % rate != 0:
        padded.append(0x00)
    padded[-1] ^= 0x80
    a = [[0] * 5 for _ in range(5)]
    for off in range(0, len(padded), rate):
        blk = padded[off:off + rate]
        for i in range(rate // 8):
            a[i % 5][i // 5] ^= int.from_bytes(blk[i * 8:(i + 1) * 8], "little")
        a = keccak_f(a)
    out = b"".join(a[i % 5][i // 5].to_bytes(8, "little") for i in range(4))
    return "0x" + out.hex()

assert keccak256(b"") == "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
assert keccak256(b"abc") == "0x4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45"

# ------------------------------------------------ ABI layout, by hand from docs/encoding.md
def word(n: int) -> bytes:
    assert 0 <= n < (1 << 256)
    return n.to_bytes(32, "big")

def bundle_bytes(records) -> bytes:
    """abi.encode(uint16 1, Record[]): head = [version][offset 0x40], tail = [len][id,price]*n."""
    out = word(1) + word(0x40) + word(len(records))
    for pid, price in records:
        assert 0 <= pid <= 0xFFFFFFFF, pid
        assert 0 <= price <= 0xFFFFFFFFFFFFFFFF, price
        out += word(pid) + word(price)
    return out

U32_MAX, U64_MAX = 0xFFFFFFFF, 0xFFFFFFFFFFFFFFFF
root = pathlib.Path(__file__).resolve().parents[1]
b1 = [(r["productId"], r["priceCents"])
      for r in json.loads((root / "fixtures" / "source-batch-1.json").read_text())]

vectors = [
    ("empty", "Empty array. Still carries the version tag and a zero length.", []),
    ("single-min", "One record at both field minimums.", [(0, 0)]),
    ("single-max", "One record at both field maximums. Above the JSON import limit on purpose.",
     [(U32_MAX, U64_MAX)]),
    ("pair-ab", "Two records in one order.", [(7, 100), (9, 200)]),
    ("pair-ba", "The same two records in the other order. Must differ from pair-ab.",
     [(9, 200), (7, 100)]),
    ("repeated-id", "The encoder does not police uniqueness; the contract does, at createJob.",
     [(5, 1), (5, 2)]),
    ("boundary-widths", "Values straddling 2^31, 2^32-1, 2^53 and 2^63.",
     [(0x7FFFFFFF, 0x1FFFFFFFFFFFFF), (0x80000000, 0x20000000000000), (U32_MAX, 0x8000000000000000)]),
    ("max-rows-32", "The documented maximum of 32 records.",
     [(i, i * 1000 + 7) for i in range(1, 33)]),
    ("source-batch-1", "The demo source fixture, in its stored (shuffled) order.", b1),
]

out = {
    "_comment": [
        "Generated by scripts/gen-golden-vectors.py, which implements the ABI layout by hand from",
        "docs/encoding.md and Keccak-256 from the permutation spec. It shares no code with ethers",
        "or solc, so agreement between these three is genuine cross-implementation agreement and",
        "not one library checked against itself.",
    ],
    "encodingVersion": 1,
    "vectors": [
        # Values are decimal STRINGS: several vectors exceed 2^53 and JSON.parse would round
        # them. The reader must use BigInt, which is the same discipline the import boundary
        # enforces on real input.
        {"name": n, "why": w, "records": [{"productId": str(p), "priceCents": str(c)} for p, c in r],
         "bundleBytes": "0x" + bundle_bytes(r).hex(), "digest": keccak256(bundle_bytes(r))}
        for n, w, r in vectors
    ],
}
(root / "fixtures" / "golden-vectors.json").write_text(json.dumps(out, indent=2) + "\n")
print(f"wrote {len(vectors)} vectors")
for v in out["vectors"]:
    print(f"  {v['name']:<16} {len(v['records']):>3} records  {v['digest'][:18]}...")
